//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string ASTEROID_COLLISION = "asteroid_collision";
        
        public const string LASER_SHOT = "laser_shot";
        
        public const string TORPEDO_SHOT = "torpedo_shot";
        
        public const string MOVEMENT = "movement";
    }
}
